language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_f5bb11657cff_key -iv $encrypted_f5bb11657cff_iv
  -in src/main/resources/firestore_access.json.enc -out src/main/resources/firestore_access.json -d
